### ISSUE TITLE
[Bug]: Cant use fabric latest update 1.19

### ISSUE THREAD

**Issue by sadlyborger** [Mrbysco/DailyDad-Server#1]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [x] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the mod

### Forge version

Fabric 0.14.6

### Mod version

DailyDad-fabric-1.19-1.4.1.jar

### Java version

Java

### Issue Description

It seems that it is registered as 1.18

### Additional Information

![image](https://user-images.githubusercontent.com/108927538/181415460-ad8d6f4b-26f0-4ff9-b6e5-ca2adbdcd419.png)
![image](https://user-images.githubusercontent.com/108927538/181415717-9d64cbab-ed04-4a67-a841-c9652bf7408a.png)

**Comment by Mrbysco** [comment]
Whoops... Will be fixed shortly

**Comment by Mrbysco** [comment]
Fixed in https://github.com/Mrbysco/DailyDad-Server/commit/2c453a2a3116ef6706c6a791b8701e28be9c2e91

**Comment by Mrbysco** [comment]
New version has been uploaded and will be up shortly
