### ISSUE TITLE
[Bug]: Forge 1.19.2 - No joke delivered on player login

### ISSUE THREAD

**Issue by ghost** [Mrbysco/DailyDad-Server#2]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Forge 43.3.13

### Minecraft version

1.19.2

### Mod version

1.3.3

### Java version

Eclipse Adoptium jre-17.0.9

### Issue Description

No joke delivered on player login. The command works fine. I was able to reproduce this on a server with Daily Dad as the only mod.

**Comment by Mrbysco** [comment]
A fix has been uploaded to CurseForge and should be available shortly

**Comment by ghost** [comment]
Thank you! 🥳
