### ISSUE TITLE
[Bug]: Crashes when starting.

### ISSUE THREAD

**Issue by PringlePot** [Mrbysco/DailyDad-Server#4]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric 0.15.11

### Minecraft version

1.21

### Mod version

2.0.1

### Java version

17

### Issue Description

In the update 2.0.1 the mod was updated to use DedicatedServerModInitializer, however this same class is also used on the "main" entrypoint causing the server to crash because DedicatedServerModInitializer cannot be cast to ModInitializer

**Comment by Mrbysco** [comment]
Whoops

**Comment by Mrbysco** [comment]
Could you test the new version?

**Comment by PringlePot** [comment]
Works! Thanks
